from packy_snark import get_snark_lines
from datetime import datetime


def generate_powershell_script(task_description):
    timestamp = datetime.utcnow().isoformat() + "Z"
    snark = get_snark_lines(3)

    return f"""# PowerShell Script generated by Packy — {timestamp}
# Task: {task_description}
#
# {snark[0]}
# {snark[1]}

Write-Output "Running task: {task_description}"

# {snark[2]}
# (Good luck — PowerShell hates you more than I do)
"""
