from packy_snark import get_snark_lines
from datetime import datetime

def generate_powershell_script(task_description):
    timestamp = datetime.utcnow().isoformat() + "Z"
    snark = get_snark_lines(2)

    return f"""# PowerShell Script generated by Packy — {timestamp}
# {snark[0]}

Write-Output "Running: {task_description}"
# {snark[1]}
"""
